/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe. No auth, no dependencies -- just confirms the process is up.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Creates a user and immediately logs them in, setting the session cookie.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Verifies credentials and starts a new session, setting the session cookie.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the caller's current session and clears the session cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Returns the user identified by the request's session cookie.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs Endpoint
         * @description Lists the caller's runs, newest first.
         */
        get: operations["list_runs_endpoint_runs_get"];
        put?: never;
        /**
         * Create Run Endpoint
         * @description Enqueues a reconciliation run and returns immediately with it in
         *     'queued' state. Poll GET /runs/{id} or GET /runs/{id}/stream for progress.
         *     Reusing an idempotency_key returns the original run instead of enqueuing a
         *     second one.
         */
        post: operations["create_run_endpoint_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Endpoint
         * @description Fetches one run's current state, metrics and forecast (the last two are
         *     null until the run completes).
         */
        get: operations["get_run_endpoint_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Result Endpoint
         * @description Fetches the full match result: matched groups and unmatched exceptions. 404 until the run completes.
         */
        get: operations["get_run_result_endpoint_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Endpoint
         * @description Streams a run's state transitions as Server-Sent Events until it reaches a terminal state.
         */
        get: operations["stream_run_endpoint_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Csv Endpoint
         * @description Exports a completed run's exceptions as a downloadable CSV. 404 until the run completes.
         */
        get: operations["export_run_csv_endpoint_runs__run_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/exceptions/{exception_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Exception Decision Endpoint
         * @description Human decisions are recorded separately from the machine's own,
         *     immutable output -- approving or rejecting an exception never rewrites
         *     the run's result or metrics.
         */
        post: operations["record_exception_decision_endpoint_runs__run_id__exceptions__exception_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Exception Decisions Endpoint
         * @description Lists every human decision recorded against this run's exceptions.
         */
        get: operations["list_exception_decisions_endpoint_runs__run_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Run Report Endpoint
         * @description The whole run as a document: verdict, run detail, the chain, every open
         *     exception worst-first, the cash position, and what it takes to reproduce
         *     the run. 404 until the run completes, for the same reason the CSV export
         *     is: there is nothing to report on a run that has not finished.
         */
        get: operations["export_run_report_endpoint_runs__run_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Endpoint
         * @description Parses the upload and asks the LLM to propose a header-to-canonical-
         *     field mapping. Nothing is persisted -- the caller confirms or overrides
         *     the mapping and re-submits the same file to /data/validate (or, to save
         *     it as a reusable dataset, to /datasets/{id}/files).
         */
        post: operations["preview_endpoint_data_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Endpoint
         * @description Applies a confirmed (possibly user-overridden) mapping and reports a
         *     file health report: how many rows are usable and why the rest aren't.
         */
        post: operations["validate_endpoint_data_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets Endpoint
         * @description Lists the caller's datasets, newest first.
         */
        get: operations["list_datasets_endpoint_datasets_get"];
        put?: never;
        /**
         * Create Dataset Endpoint
         * @description A "generated" dataset is built and persisted synchronously (it's a
         *     pure, fast, in-memory computation) and comes back already "ready". An
         *     "uploaded" dataset starts empty -- the caller adds each role's file via
         *     POST /datasets/{id}/files, and it becomes "ready" once all four are in.
         */
        post: operations["create_dataset_endpoint_datasets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Endpoint
         * @description Fetches one dataset, including per-role file status.
         */
        get: operations["get_dataset_endpoint_datasets__dataset_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Dataset Endpoint
         * @description Deletes a dataset, every file in it, and every run made from it.
         *
         *     The runs go too, deliberately. A run's scoreboard cites records by id and
         *     its exceptions quote evidence out of them; once the dataset is gone none
         *     of that can be re-derived, and a reconciliation you cannot re-derive is
         *     not evidence of anything. Better to remove it than to leave a figure on
         *     screen that nothing backs any more.
         *
         *     A run still in flight goes too, which cancels it: the worker looks its run
         *     up before doing any work and stops when it finds nothing. Refusing instead
         *     would let a worker that died holding a queued run block its dataset from
         *     ever being deleted.
         */
        delete: operations["delete_dataset_endpoint_datasets__dataset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Dataset File Endpoint
         * @description Applies a confirmed mapping (from /data/preview) and persists both the
         *     original file and the validated canonical records for this role, then
         *     recomputes whether the dataset is ready to run.
         */
        post: operations["upload_dataset_file_endpoint_datasets__dataset_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/files/{role}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset File Records Endpoint
         * @description Pages through a dataset file's canonical (post-mapping) records.
         */
        get: operations["get_dataset_file_records_endpoint_datasets__dataset_id__files__role__records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/files/{role}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset File Raw Endpoint
         * @description Downloads the original file as uploaded for this role -- not the canonical records derived from it.
         */
        get: operations["get_dataset_file_raw_endpoint_datasets__dataset_id__files__role__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{dataset_id}/files/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Dataset File Endpoint
         * @description Removes one role's file. The dataset survives one role lighter, and
         *     drops out of "ready" because a run needs all four.
         *
         *     Existing runs are left alone: they were scored against the records as they
         *     stood, and rewriting history to match a later edit would make every
         *     scoreboard provisional.
         */
        delete: operations["delete_dataset_file_endpoint_datasets__dataset_id__files__role__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Endpoint
         * @description Answers a question about a run, grounded in that run's data. `degraded`
         *     is true when no model could be reached (quota exhausted or all attempts
         *     failed) and a fallback answer was returned instead.
         */
        post: operations["ask_endpoint_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Stream Endpoint
         * @description The same answer, delivered as it is written.
         *
         *     Server-sent events over POST rather than EventSource, because the
         *     question belongs in a body and not in a URL. The frame format is the
         *     same one the run stream uses, so the Next.js proxy passes it through
         *     untouched.
         */
        post: operations["ask_stream_endpoint_ask_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Run Id */
            run_id: string;
            /** Question */
            question: string;
        };
        /** AskResponseOut */
        AskResponseOut: {
            /** Answer */
            answer: string;
            /** Degraded */
            degraded: boolean;
        };
        /** Body_preview_endpoint_data_preview_post */
        Body_preview_endpoint_data_preview_post: {
            /**
             * Role
             * @description One of 'ledger', 'gateway', 'settlement', 'bank'.
             */
            role: string;
            /** File */
            file: string;
        };
        /** Body_upload_dataset_file_endpoint_datasets__dataset_id__files_post */
        Body_upload_dataset_file_endpoint_datasets__dataset_id__files_post: {
            /**
             * Role
             * @description One of 'ledger', 'gateway', 'settlement', 'bank'.
             */
            role: string;
            /**
             * Mapping
             * @description JSON-encoded list of {source_header, canonical_field, confidence}
             */
            mapping: string;
            /** File */
            file: string;
        };
        /** Body_validate_endpoint_data_validate_post */
        Body_validate_endpoint_data_validate_post: {
            /**
             * Role
             * @description One of 'ledger', 'gateway', 'settlement', 'bank'.
             */
            role: string;
            /**
             * Mapping
             * @description JSON-encoded list of {source_header, canonical_field, confidence}
             */
            mapping: string;
            /** File */
            file: string;
        };
        /**
         * CashForecast
         * @description A 14-day projection over the corpus's own settlement window (not the
         *     calendar "today" -- this is a historical synthetic corpus, not a live
         *     ledger), computed once by the worker so the frontend never sums a paise
         *     amount itself.
         */
        CashForecast: {
            /** Days */
            days: components["schemas"]["ForecastDay"][];
            /** Unrecognised Cash */
            unrecognised_cash: number;
        };
        /** ClassScore */
        ClassScore: {
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** Count */
            count: number;
        };
        /** Credentials */
        Credentials: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** DatasetCreate */
        DatasetCreate: {
            /** Name */
            name: string;
            /**
             * Source
             * @enum {string}
             */
            source: "generated" | "uploaded";
            /** Seed */
            seed?: number | null;
            /** Size */
            size?: number | null;
        };
        /**
         * DatasetDeletedOut
         * @description What a delete removed, stated rather than implied: a caller that asked
         *     to remove one dataset is entitled to know how many runs went with it.
         */
        DatasetDeletedOut: {
            /** Dataset Id */
            dataset_id: string;
            /** Runs Deleted */
            runs_deleted: number;
        };
        /** DatasetFileOut */
        DatasetFileOut: {
            /** Role */
            role: string;
            /** Raw Filename */
            raw_filename: string | null;
            /** Has Raw */
            has_raw: boolean;
            /** Row Count */
            row_count: number;
            /** Valid Count */
            valid_count: number;
        };
        /** DatasetFileUploadOut */
        DatasetFileUploadOut: {
            dataset: components["schemas"]["DatasetOut"];
            /** Total Rows */
            total_rows: number;
            /** Valid Count */
            valid_count: number;
            /** Errors */
            errors: components["schemas"]["RowErrorOut"][];
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** DatasetOut */
        DatasetOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Seed */
            seed: number | null;
            /** Size */
            size: number | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files: components["schemas"]["DatasetFileOut"][];
            /**
             * Run Count
             * @default 0
             */
            run_count: number;
        };
        /** DatasetRecordsOut */
        DatasetRecordsOut: {
            /** Role */
            role: string;
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Records */
            records: {
                [key: string]: unknown;
            }[];
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note?: string | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Exception Id */
            exception_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Evidence */
        Evidence: {
            /** Field */
            field: string;
            /** Value */
            value: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * ExceptionCode
         * @enum {string}
         */
        ExceptionCode: "AMT_MISMATCH_UNEXPLAINED" | "FEE_GST_DELTA_UNCONFIRMED" | "DATE_OUTSIDE_WINDOW" | "MISSING_IN_BANK" | "MISSING_IN_LEDGER" | "DUPLICATE_CANDIDATE" | "PARTIAL_SETTLEMENT_OPEN" | "REFUND_UNLINKED" | "CHARGEBACK_UNLINKED" | "UNIDENTIFIED_CREDIT" | "AMBIGUOUS_MULTI_CANDIDATE" | "LLM_PROPOSAL_FAILED_VERIFY" | "SOURCE_PARSE_INCOMPLETE";
        /** Exception_ */
        Exception_: {
            /** Id */
            id: string;
            code: components["schemas"]["ExceptionCode"];
            /**
             * Severity
             * @enum {integer}
             */
            severity: 1 | 2 | 3;
            /** Amount At Risk */
            amount_at_risk: number;
            /** Records */
            records: components["schemas"]["RecordRef"][];
            /** Attempted */
            attempted: string[];
            /** Explanation */
            explanation?: string | null;
            /** Suggested Action */
            suggested_action?: string | null;
            rejected_proposal?: components["schemas"]["RejectedProposal"] | null;
        };
        /** FieldMappingOut */
        FieldMappingOut: {
            /** Source Header */
            source_header: string;
            /** Canonical Field */
            canonical_field: string | null;
            /** Confidence */
            confidence: number;
        };
        /** ForecastDay */
        ForecastDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Recognised */
            recognised: number;
            /** Blocked */
            blocked: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MatchGroup */
        MatchGroup: {
            /** Id */
            id: string;
            /** Invoice Ids */
            invoice_ids: string[];
            /** Payment Ids */
            payment_ids: string[];
            /** Settlement Id */
            settlement_id?: string | null;
            /** Bank Line Id */
            bank_line_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "auto" | "assisted" | "open";
            pass_id: components["schemas"]["PassId"];
            /** Confidence */
            confidence: number;
            /** Residual */
            residual: number;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /**
         * PassId
         * @enum {string}
         */
        PassId: "P0" | "P1" | "P2" | "P3" | "P4" | "LLM";
        /** PreviewOut */
        PreviewOut: {
            /** Headers */
            headers: string[];
            /** Sample Rows */
            sample_rows: {
                [key: string]: string;
            }[];
            /** Mapping */
            mapping: components["schemas"]["FieldMappingOut"][];
            /** Canonical Fields */
            canonical_fields: string[];
        };
        /** RecordRef */
        RecordRef: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "invoice" | "payment" | "settlement" | "bank_line";
            /** Id */
            id: string;
        };
        /** RejectedProposal */
        RejectedProposal: {
            /**
             * Proposed By
             * @constant
             */
            proposed_by: "llm";
            /** Match Group */
            match_group: {
                [key: string]: unknown;
            };
            /** Failed Check */
            failed_check: string;
        };
        /** RowErrorOut */
        RowErrorOut: {
            /** Row Number */
            row_number: number;
            /** Reason */
            reason: string;
        };
        /** RunCreate */
        RunCreate: {
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "dataset";
            /** Seed */
            seed?: number | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Size */
            size?: number | null;
            /**
             * Mutations
             * @description Adversarial corruptions to apply to the corpus before matching, e.g. 'shift_date:60' or 'alter_amount:-250000'.
             */
            mutations?: string[] | null;
            /**
             * Idempotency Key
             * @description Replaying the same key returns the existing run instead of starting a new one.
             */
            idempotency_key?: string | null;
        };
        /** RunMetrics */
        RunMetrics: {
            /** Auto Rate */
            auto_rate: number;
            /** Assist Rate */
            assist_rate: number;
            /** Open Rate */
            open_rate: number;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** False Matches */
            false_matches?: number | null;
            /** By Class */
            by_class?: {
                [key: string]: components["schemas"]["ClassScore"];
            } | null;
            /** Records */
            records: number;
            /** Open Exceptions */
            open_exceptions: number;
            /** Amount At Risk */
            amount_at_risk: number;
            /** Throughput Rps */
            throughput_rps: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Llm Requests */
            llm_requests: number;
            /** Llm Tokens */
            llm_tokens: number;
            /** Llm Degraded */
            llm_degraded: boolean;
            /** Output Hash */
            output_hash: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Dataset Id */
            dataset_id: string | null;
            /** Mutations */
            mutations: string[] | null;
            /** State */
            state: string;
            /** Error */
            error: string | null;
            metrics: components["schemas"]["RunMetrics"] | null;
            forecast: components["schemas"]["CashForecast"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunResultOut */
        RunResultOut: {
            /** Groups */
            groups: components["schemas"]["MatchGroup"][];
            /** Exceptions */
            exceptions: components["schemas"]["Exception_"][];
            /** Output Hash */
            output_hash: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidateOut */
        ValidateOut: {
            /** Total Rows */
            total_rows: number;
            /** Valid Count */
            valid_count: number;
            /** Errors */
            errors: components["schemas"]["RowErrorOut"][];
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
            /**
             * Notes
             * @default []
             */
            notes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_runs_endpoint_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
        };
    };
    create_run_endpoint_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_endpoint_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_endpoint_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_endpoint_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream of {state, error?} frames, replaying missed transitions on connect. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_csv_endpoint_runs__run_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run's exceptions as a CSV attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_exception_decision_endpoint_runs__run_id__exceptions__exception_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exception_decisions_endpoint_runs__run_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_report_endpoint_runs__run_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The run's full report as a branded PDF attachment. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_endpoint_data_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_endpoint_data_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_endpoint_data_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_endpoint_data_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_endpoint_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"][];
                };
            };
        };
    };
    create_dataset_endpoint_datasets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_endpoint_datasets__dataset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_endpoint_datasets__dataset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetDeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_dataset_file_endpoint_datasets__dataset_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_dataset_file_endpoint_datasets__dataset_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetFileUploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_file_records_endpoint_datasets__dataset_id__files__role__records_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                dataset_id: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetRecordsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_file_raw_endpoint_datasets__dataset_id__files__role__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The original uploaded file, byte-for-byte, as an attachment download. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dataset_file_endpoint_datasets__dataset_id__files__role__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dataset_id: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_endpoint_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_stream_endpoint_ask_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description text/event-stream of {type, ...} frames; render only the final 'done' event's answer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
