/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs Endpoint */
        get: operations["list_runs_endpoint_runs_get"];
        put?: never;
        /** Create Run Endpoint */
        post: operations["create_run_endpoint_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Endpoint */
        get: operations["get_run_endpoint_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result Endpoint */
        get: operations["get_run_result_endpoint_runs__run_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Endpoint */
        get: operations["stream_run_endpoint_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Run Csv Endpoint */
        get: operations["export_run_csv_endpoint_runs__run_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/exceptions/{exception_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record Exception Decision Endpoint
         * @description Human decisions are recorded separately from the machine's own,
         *     immutable output -- approving or rejecting an exception never rewrites
         *     the run's result or metrics.
         */
        post: operations["record_exception_decision_endpoint_runs__run_id__exceptions__exception_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exception Decisions Endpoint */
        get: operations["list_exception_decisions_endpoint_runs__run_id__decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Endpoint
         * @description Parses the upload and asks the LLM to propose a header-to-canonical-
         *     field mapping. Nothing is persisted -- the caller confirms or overrides
         *     the mapping and re-submits the same file to /data/validate.
         */
        post: operations["preview_endpoint_data_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Endpoint
         * @description Applies a confirmed (possibly user-overridden) mapping and reports a
         *     file health report: how many rows are usable and why the rest aren't.
         */
        post: operations["validate_endpoint_data_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask Endpoint */
        post: operations["ask_endpoint_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AskRequest */
        AskRequest: {
            /** Run Id */
            run_id: string;
            /** Question */
            question: string;
        };
        /** AskResponseOut */
        AskResponseOut: {
            /** Answer */
            answer: string;
            /** Degraded */
            degraded: boolean;
        };
        /** Body_preview_endpoint_data_preview_post */
        Body_preview_endpoint_data_preview_post: {
            /** Role */
            role: string;
            /** File */
            file: string;
        };
        /** Body_validate_endpoint_data_validate_post */
        Body_validate_endpoint_data_validate_post: {
            /** Role */
            role: string;
            /**
             * Mapping
             * @description JSON-encoded list of {source_header, canonical_field, confidence}
             */
            mapping: string;
            /** File */
            file: string;
        };
        /**
         * CashForecast
         * @description A 14-day projection over the corpus's own settlement window (not the
         *     calendar "today" -- this is a historical synthetic corpus, not a live
         *     ledger), computed once by the worker so the frontend never sums a paise
         *     amount itself.
         */
        CashForecast: {
            /** Days */
            days: components["schemas"]["ForecastDay"][];
            /** Unrecognised Cash */
            unrecognised_cash: number;
        };
        /** ClassScore */
        ClassScore: {
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** Count */
            count: number;
        };
        /** Credentials */
        Credentials: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** DecisionIn */
        DecisionIn: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note?: string | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Exception Id */
            exception_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Evidence */
        Evidence: {
            /** Field */
            field: string;
            /** Value */
            value: string;
            /** Source Id */
            source_id: string;
        };
        /**
         * ExceptionCode
         * @enum {string}
         */
        ExceptionCode: "AMT_MISMATCH_UNEXPLAINED" | "FEE_GST_DELTA_UNCONFIRMED" | "DATE_OUTSIDE_WINDOW" | "MISSING_IN_BANK" | "MISSING_IN_LEDGER" | "DUPLICATE_CANDIDATE" | "PARTIAL_SETTLEMENT_OPEN" | "REFUND_UNLINKED" | "CHARGEBACK_UNLINKED" | "UNIDENTIFIED_CREDIT" | "AMBIGUOUS_MULTI_CANDIDATE" | "LLM_PROPOSAL_FAILED_VERIFY" | "SOURCE_PARSE_INCOMPLETE";
        /** Exception_ */
        Exception_: {
            /** Id */
            id: string;
            code: components["schemas"]["ExceptionCode"];
            /**
             * Severity
             * @enum {integer}
             */
            severity: 1 | 2 | 3;
            /** Amount At Risk */
            amount_at_risk: number;
            /** Records */
            records: components["schemas"]["RecordRef"][];
            /** Attempted */
            attempted: string[];
            /** Explanation */
            explanation?: string | null;
            /** Suggested Action */
            suggested_action?: string | null;
            rejected_proposal?: components["schemas"]["RejectedProposal"] | null;
        };
        /** FieldMappingOut */
        FieldMappingOut: {
            /** Source Header */
            source_header: string;
            /** Canonical Field */
            canonical_field: string | null;
            /** Confidence */
            confidence: number;
        };
        /** ForecastDay */
        ForecastDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Recognised */
            recognised: number;
            /** Blocked */
            blocked: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MatchGroup */
        MatchGroup: {
            /** Id */
            id: string;
            /** Invoice Ids */
            invoice_ids: string[];
            /** Payment Ids */
            payment_ids: string[];
            /** Settlement Id */
            settlement_id?: string | null;
            /** Bank Line Id */
            bank_line_id?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "auto" | "assisted" | "open";
            pass_id: components["schemas"]["PassId"];
            /** Confidence */
            confidence: number;
            /** Residual */
            residual: number;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /**
         * PassId
         * @enum {string}
         */
        PassId: "P0" | "P1" | "P2" | "P3" | "P4" | "LLM";
        /** PreviewOut */
        PreviewOut: {
            /** Headers */
            headers: string[];
            /** Sample Rows */
            sample_rows: {
                [key: string]: string;
            }[];
            /** Mapping */
            mapping: components["schemas"]["FieldMappingOut"][];
            /** Canonical Fields */
            canonical_fields: string[];
        };
        /** RecordRef */
        RecordRef: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "invoice" | "payment" | "settlement" | "bank_line";
            /** Id */
            id: string;
        };
        /** RejectedProposal */
        RejectedProposal: {
            /**
             * Proposed By
             * @constant
             */
            proposed_by: "llm";
            /** Match Group */
            match_group: {
                [key: string]: unknown;
            };
            /** Failed Check */
            failed_check: string;
        };
        /** RowErrorOut */
        RowErrorOut: {
            /** Row Number */
            row_number: number;
            /** Reason */
            reason: string;
        };
        /** RunCreate */
        RunCreate: {
            /**
             * Source
             * @enum {string}
             */
            source: "demo" | "dataset";
            /** Seed */
            seed?: number | null;
            /** Dataset Id */
            dataset_id?: string | null;
            /** Size */
            size?: number | null;
            /** Mutations */
            mutations?: string[] | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
        };
        /** RunMetrics */
        RunMetrics: {
            /** Auto Rate */
            auto_rate: number;
            /** Assist Rate */
            assist_rate: number;
            /** Open Rate */
            open_rate: number;
            /** Precision */
            precision?: number | null;
            /** Recall */
            recall?: number | null;
            /** False Matches */
            false_matches?: number | null;
            /** By Class */
            by_class?: {
                [key: string]: components["schemas"]["ClassScore"];
            } | null;
            /** Records */
            records: number;
            /** Open Exceptions */
            open_exceptions: number;
            /** Amount At Risk */
            amount_at_risk: number;
            /** Throughput Rps */
            throughput_rps: number;
            /** P50 Ms */
            p50_ms: number;
            /** P95 Ms */
            p95_ms: number;
            /** Llm Requests */
            llm_requests: number;
            /** Llm Tokens */
            llm_tokens: number;
            /** Llm Degraded */
            llm_degraded: boolean;
            /** Output Hash */
            output_hash: string;
        };
        /** RunOut */
        RunOut: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** State */
            state: string;
            /** Error */
            error: string | null;
            metrics: components["schemas"]["RunMetrics"] | null;
            forecast: components["schemas"]["CashForecast"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RunResultOut */
        RunResultOut: {
            /** Groups */
            groups: components["schemas"]["MatchGroup"][];
            /** Exceptions */
            exceptions: components["schemas"]["Exception_"][];
            /** Output Hash */
            output_hash: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** ValidateOut */
        ValidateOut: {
            /** Total Rows */
            total_rows: number;
            /** Valid Count */
            valid_count: number;
            /** Errors */
            errors: components["schemas"]["RowErrorOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_runs_endpoint_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"][];
                };
            };
        };
    };
    create_run_endpoint_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_endpoint_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_endpoint_runs__run_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_endpoint_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_csv_endpoint_runs__run_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_exception_decision_endpoint_runs__run_id__exceptions__exception_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                exception_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_exception_decisions_endpoint_runs__run_id__decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_endpoint_data_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_endpoint_data_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_endpoint_data_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_endpoint_data_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_endpoint_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
