"""add forecast_json to runs

Revision ID: 55780510d666
Revises: 9729b626584b
Create Date: 2026-08-31 21:28:44.898735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55780510d666'
down_revision: Union[str, Sequence[str], None] = '9729b626584b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('forecast_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'forecast_json')
    # ### end Alembic commands ###
