"""add exception_decisions table

Revision ID: 83ddb5c89b81
Revises: 55780510d666
Create Date: 2026-08-31 21:41:29.525282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ddb5c89b81'
down_revision: Union[str, Sequence[str], None] = '55780510d666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exception_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('exception_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exception_decisions_run_exception', 'exception_decisions', ['run_id', 'exception_id'], unique=True)
    op.create_index(op.f('ix_exception_decisions_run_id'), 'exception_decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exception_decisions_run_id'), table_name='exception_decisions')
    op.drop_index('ix_exception_decisions_run_exception', table_name='exception_decisions')
    op.drop_table('exception_decisions')
    # ### end Alembic commands ###
